import 'dart:async';
import 'dart:convert';

///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class Hymn {
/*
{
  "id": 0,
  "hymn_no": "1",
  "content": "INTROIT\n1. 11s 10s\n1. God is a Spirit, those who worship Him\nIn Spirit and truth must bow down their knees\nThou who dwellest amidst the Cherubims\nDraw nigh to us as we draw nigh to Thee. Amen.\n"
} 
*/

  int id = 0;
  String hymnNo = "";
  String content = "";

  Hymn({
    required this.id,
    required this.hymnNo,
    required this.content,
  });

  Hymn.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    hymnNo = json['hymn_no']?.toString() ?? "";
    content = json['content']?.toString() ?? "";
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['hymn_no'] = hymnNo;
    data['content'] = content;
    return data;
  }
}

class Hymns {
  List<Hymn> hymns = [];

  Hymns() : super();

  Hymns.fromJson(List<dynamic> json) {
    for (var hymn in json) {
      hymns.add(Hymn.fromJson(hymn));
    }
  }
}
